name: Sync RFCs

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync RFCs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync txt format
        run: rsync -avz --delete rsync.ietf.org::rfc/rfc[0-9]*.txt ./rfc/

      - name: Sync RFCs in XML format
        run: rsync -avz --delete rsync.ietf.org::rfc/rfc[0-9]*.xml ./rfc/

      - name: Sync RFCs in HTML format
        run: rsync -avz --delete rsync.ietf.org::rfc/rfc[0-9]*.html ./rfc/

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Sync RFCs" && git push)
