name: Test text output

on:
  workflow_run:
    workflows: [Sync RFCs]
    types:
      - completed
  workflow_dispatch:
    inputs:
      custom-run:
        description: 'Custom run'
        required: true
        default: 'false'
      repository:
        description: 'GitHub repository'
        required: true
        default: 'ietf-tools/xml2rfc'
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

jobs:
  extract-attributes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install latest xml2rfc
      if: ${{ github.event.inputs['custom-run'] == 'false' }}
      run: |
        python -m pip install --upgrade pip
        pip install xml2rfc

    - name: Install custom xml2rfc version
      if: ${{ github.event.inputs['custom-run'] == 'true' }}
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/${{ github.event.inputs.repository }}.git@${{ github.event.inputs.branch }}

    - name: Test text output
      run: python text_check.py

    - name: Commit changes
      if: ${{ github.event.inputs['custom-run'] == 'false' }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add text_results
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Add text test diffs" && git push)

    - name: Commit custom changes
      if: ${{ github.event.inputs['custom-run'] == 'true' }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        mv text_results text_tesutls.$GITHUB_RUN_ID
        git add text_results.$GITHUB_RUN_ID
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Add text test diffs" && git push)

