name: Test text output

on:
  workflow_run:
    workflows: [Sync RFCs]
    types:
      - completed
  workflow_dispatch:

jobs:
  extract-attributes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xml2rfc

    - name: Test text output
      run: python text_check.py

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add text_results
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Add text test diffs" && git push)

